# Generated by Django 3.2.9 on 2021-11-05 06:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0002_placeimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='placeId',
            field=models.CharField(default=None, max_length=200, verbose_name='Идентификатор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='project',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='imgs', to='places.place', verbose_name='Проект'),
        ),
    ]
