# Generated by Django 3.2.9 on 2021-11-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0004_alter_place_placeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='place',
            name='placeId',
            field=models.CharField(default=None, max_length=200, verbose_name='Идентификатор'),
        ),
    ]
