# Generated by Django 3.2.9 on 2021-11-06 11:54

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0005_alter_place_placeid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='placeimage',
            options={'ordering': ['number']},
        ),
        migrations.AlterField(
            model_name='place',
            name='description_long',
            field=tinymce.models.HTMLField(verbose_name='Длинное описание'),
        ),
        migrations.AlterField(
            model_name='place',
            name='placeId',
            field=models.CharField(blank=True, default=None, max_length=200, verbose_name='Идентификатор'),
        ),
        migrations.AlterField(
            model_name='placeimage',
            name='number',
            field=models.IntegerField(blank=True, default=0, verbose_name='Номер'),
        ),
    ]
