# Generated by Django 3.2.9 on 2021-11-08 18:10

from django.db import migrations


def change_null_to_empty_string_in_place_description_long(apps, schema_editor):
    Place = apps.get_model('places', 'Place')
    for place in Place.objects.all():
        if not place.description_long:
            place.description_long = ''
            place.save()


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0016_auto_20211108_1550'),
    ]

    operations = [
        migrations.RunPython(change_null_to_empty_string_in_place_description_long)
    ]
